-- Copyright (c) 2026 Scott Armstrong.
-- Released under Apache 2.0 license.

module

public import ESS.Linear.BUShortEarlyIntegral
public import ESS.Linear.BUShortEnergyL2

/-!
# Weighted initial-time strip majorant

The weighted quadratic term generated by the lower-time cutoff is
bounded by the normalized trace mass on the containing spatial ball.
-/

@[expose] public section

set_option autoImplicit false

open MeasureTheory Set CKN CKN.Foundation.Parabolic

noncomputable section

namespace ESS

/-- The weighted quadratic mass of the shrinking strip is controlled by
the quadratic trace mass on the larger ball. -/
theorem bu_short_early_weighted_majorant_le
    (scale R ε a Cw : ℝ) (hscale : 0 < scale) (hscale1 : scale ≤ 1)
    (hR : 0 < R) (hε : 0 < ε) (hCw : 0 ≤ Cw)
    (hweight : ∀ z ∈ buShortFixedCylinder R,
      buShortCarlemanWeight a z ≤ Cw)
    (v : ParabolicPoint → Vec3)
    (Dv : ParabolicPoint → Fin 3 → Vec3)
    (hv : MemLp v 2 (volume.restrict
      (buCutSupportSet (buShortFullCutoff scale R hR ε))))
    (hDv : MemLp Dv 2 (volume.restrict
      (buCutSupportSet (buShortFullCutoff scale R hR ε))))
    (hfInt : IntegrableOn (fun z => vec3EuclideanNorm (v z) ^ 2)
      (spaceTimeSet (buShortTraceBall R)
        (Icc (1 / 2 + ε) (1 / 2 + 2 * ε))) volume) :
    let K := buCutSupportSet (buShortFullCutoff scale R hR ε)
    let S := spaceTimeSet (buShortTraceBall R)
      (Icc (1 / 2 + ε) (1 / 2 + 2 * ε))
    let f : ParabolicPoint → ℝ := fun z => vec3EuclideanNorm (v z) ^ 2
    (∫ z in K, buShortCarlemanWeight a z * (8 / ε) ^ 2 *
      S.indicator f z ∂(volume : Measure ParabolicPoint)) ≤
      (Cw * (8 / ε) ^ 2) *
        (∫ q in buShortTraceBall R ×ˢ
          Icc (1 / 2 + ε) (1 / 2 + 2 * ε),
          vec3EuclideanNorm (v (parabolicHomeomorph.symm q)) ^ 2
          ∂(volume : Measure (Vec3 × ℝ))) := by
  let K := buCutSupportSet (buShortFullCutoff scale R hR ε)
  let S := spaceTimeSet (buShortTraceBall R)
    (Icc (1 / 2 + ε) (1 / 2 + 2 * ε))
  let f : ParabolicPoint → ℝ := fun z => vec3EuclideanNorm (v z) ^ 2
  let W := buShortCarlemanWeight a
  let C := Cw * (8 / ε) ^ 2
  have hKcompact : IsCompact K :=
    (bu_short_cutoff_support_geometry scale R ε hscale hscale1 hR hε).1
  have hKmeas : MeasurableSet K := hKcompact.isClosed.measurableSet
  have hSmeas : MeasurableSet S := by
    change MeasurableSet (parabolicHomeomorph ⁻¹'
      (buShortTraceBall R ×ˢ Icc (1 / 2 + ε) (1 / 2 + 2 * ε)))
    exact (((buShortTraceBall_geometry hR).1.measurableSet).prod
      measurableSet_Icc).preimage parabolicHomeomorph.measurable
  have hfIntK : IntegrableOn f K volume :=
    (bu_memLp_quadratic_energy_integrable K v Dv hv hDv).1
  have hIndInt : IntegrableOn (S.indicator f) K volume :=
    hfIntK.indicator hSmeas
  have hGInt : IntegrableOn (fun z => W z * (8 / ε) ^ 2 *
      S.indicator f z) K volume := by
    have hscaled : IntegrableOn
        (fun z => (8 / ε) ^ 2 * S.indicator f z) K volume :=
      hIndInt.const_mul _
    have hWInt := bu_integrableOn_mul_continuous_compact hKcompact
      (fun z => (8 / ε) ^ 2 * S.indicator f z) W hscaled
      (buShortCarlemanWeight_continuousOn_support
        scale R ε a hscale hscale1 hR hε)
    convert hWInt using 1
    funext z
    ring
  have hC : 0 ≤ C := by dsimp [C]; positivity
  have hfixed := buShortCutSupport_subset_fixedCylinder
    scale R ε hscale hscale1 hR hε
  have hpoint : ∀ z ∈ K,
      W z * (8 / ε) ^ 2 * S.indicator f z ≤ C * S.indicator f z := by
    intro z hz
    have hW := hweight z (hfixed hz)
    have hF : 0 ≤ S.indicator f z := by
      by_cases hzS : z ∈ S
      · simpa [Set.indicator, hzS, f] using
          (sq_nonneg (vec3EuclideanNorm (v z)))
      · simp [Set.indicator, hzS]
    have hscale0 : 0 ≤ (8 / ε) ^ 2 * S.indicator f z := by positivity
    have h := mul_le_mul_of_nonneg_right hW hscale0
    dsimp [C]
    nlinarith only [h]
  have hmain := bu_short_early_integral_le_trace hKmeas hSmeas
    hfInt hGInt (fun z => sq_nonneg _) C hC hpoint
  change (∫ z in K, W z * (8 / ε) ^ 2 * S.indicator f z
      ∂(volume : Measure ParabolicPoint)) ≤
    C * (∫ z in S, f z ∂(volume : Measure ParabolicPoint)) at hmain
  rw [setIntegral_parabolic_to_product] at hmain
  exact hmain

end ESS
