#!/usr/bin/env python3
# Copyright (c) 2026 Scott Armstrong.
# Released under Apache 2.0 license.
"""Check project declaration axioms through one generated Lean probe.

The default mode imports every tracked ESS Lean module and prints the axioms
of every named public declaration found by a namespace-aware source lexer.
Only propext, Classical.choice and Quot.sound are accepted; there are no
exceptions.  ``--changed`` checks the supplied Lean files; ``--root`` selects a
different checkout.  The generated probe is temporary and uses the pinned
Lean toolchain.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
from typing import Iterable


HEADER = "-- generated by scripts/check_axioms.py\n"
IDENT = r"[\w][\w']*"
QUALIFIED = rf"{IDENT}(?:\.{IDENT})*"
NAMESPACE = re.compile(rf"\bnamespace\s+({QUALIFIED})\b")
SECTION = re.compile(r"\bsection(?:\s+[A-Za-z_][A-Za-z0-9_']*)?")
# ``end`` is a command, not a prefix that may occur inside an identifier.
# It is matched against a complete source line in ``public_declarations``.
END = re.compile(rf"^[ \t]*end(?:[ \t]+{IDENT}(?:\.{IDENT})*)?[ \t]*$")
DECL = re.compile(
    r"^[ \t]*(?:@\[[^\]\n]*\][ \t]*)*"
    r"(?:(?:(private|protected|scoped|local)\s+)|"
    r"(?:public|meta|noncomputable|unsafe|partial)\s+)*"
    r"(theorem|lemma|def|abbrev|opaque|structure|class|inductive|instance)\b"
    rf"(?:\s+({QUALIFIED}))?"
)
AXIOMS = re.compile(
    rf"^[ \t]*(?:'(?P<quoted>{QUALIFIED})'|(?P<plain>{QUALIFIED}))"
    r"[ \t]+(?:(?:depends on axioms:[ \t]*\[(?P<body>.*?)\])|"
    r"does not depend on any axioms)",
    re.MULTILINE | re.DOTALL,
)


def strip_comments(text: str) -> str:
    """Blank nested block and line comments before source lexing.

    String and character literals are skipped while looking for comments, so
    comment markers in a literal are not mistaken for source comments.  The
    literals are blanked as well because the declaration lexer must inspect
    commands only.
    """
    out = list(text)

    def blank(start: int, end: int) -> None:
        for index in range(start, end):
            if out[index] != "\n":
                out[index] = " "

    index, size = 0, len(text)
    while index < size:
        if text.startswith("--", index):
            end = text.find("\n", index)
            end = size if end == -1 else end
            blank(index, end)
            index = end
        elif text.startswith("/-", index):
            start, depth = index, 1
            index += 2
            while index < size and depth:
                if text.startswith("/-", index):
                    depth, index = depth + 1, index + 2
                elif text.startswith("-/", index):
                    depth, index = depth - 1, index + 2
                else:
                    index += 1
            blank(start, index)
        elif text.startswith('"""', index):
            start = index
            end = text.find('"""', index + 3)
            index = size if end == -1 else end + 3
            blank(start, index)
        elif text[index] == '"':
            start, index = index, index + 1
            while index < size:
                if text[index] == "\\":
                    index += 2
                elif text[index] == '"':
                    index += 1
                    break
                else:
                    index += 1
            blank(start, min(index, size))
        elif text[index] == "'" and (
            index == 0 or not (text[index - 1].isalnum() or text[index - 1] in "_'")
        ) and (
            # A character literal is 'c' or an escape '\...' closed within a few
            # characters; a lone apostrophe (as in the notation ∑' or a prime
            # after a symbol) is not a literal.
            (index + 2 < size and text[index + 1] != "\\" and text[index + 1] != "\n"
             and text[index + 2] == "'")
            or (index + 1 < size and text[index + 1] == "\\"
                and "'" in text[index + 2:index + 12].split("\n", 1)[0])
        ):
            start, index = index, index + 1
            while index < size:
                if text[index] == "\\":
                    index += 2
                elif text[index] == "'":
                    index += 1
                    break
                else:
                    index += 1
            blank(start, min(index, size))
        else:
            index += 1
    return "".join(out)


def code_mask(text: str) -> str:
    """Compatibility name for the comment/string mask used by source lexers."""
    return strip_comments(text)


def module_name(root: Path, path: Path) -> str:
    return ".".join(path.resolve().relative_to(root.resolve()).with_suffix("").parts)


def public_declarations(root: Path, path: Path) -> list[str]:
    namespaces: list[str] = []
    blocks: list[tuple[str, int]] = []
    found: list[str] = []
    for line in strip_comments(path.read_text(encoding="utf-8")).splitlines():
        # Lean permits several commands on one physical line.  In particular,
        # ``noncomputable section namespace ESS`` is a legal one-line opening
        # form.  Process command-like tokens in source order
        # rather than requiring each command to occupy the whole line.
        events: list[tuple[int, str, re.Match[str]]] = []
        events.extend((match.start(), "namespace", match) for match in NAMESPACE.finditer(line))
        events.extend((match.start(), "section", match) for match in SECTION.finditer(line))
        end_command = END.match(line)
        if end_command is not None:
            events.append((end_command.start(), "end", end_command))
        # Top-level Lean commands begin in column zero.  Requiring that here
        # prevents tactic-local/where-local syntax and identifier fragments
        # (for example `hdef` or `norm_def`) from becoming public probes.
        declaration = DECL.match(line) if not line[:1].isspace() else None
        if declaration is not None:
            events.append((declaration.start(), "declaration", declaration))
        for _position, kind, match in sorted(events, key=lambda item: item[0]):
            if kind == "namespace":
                parts = match.group(1).split(".")
                namespaces.extend(parts)
                blocks.append(("namespace", len(parts)))
            elif kind == "section":
                blocks.append(("section", 0))
            elif kind == "end":
                if blocks:
                    block, count = blocks.pop()
                    if block == "namespace" and count:
                        del namespaces[-count:]
            else:
                modifier, _kind, name = match.groups()
                if modifier not in {"private", "local"} and name is not None:
                    # ``_root_.X`` names X itself, whatever namespace is open.
                    found.append(name.removeprefix("_root_.") if name.startswith("_root_.")
                                 else ".".join([*namespaces, *name.split(".")]))
    return found


def namespace_candidates(root: Path, path: Path) -> list[str]:
    """Return namespace prefixes that can qualify a bare declaration name."""
    prefixes: list[str] = []

    def add_prefixes(namespace: str) -> None:
        parts = namespace.split(".")
        for count in range(len(parts), 0, -1):
            prefix = ".".join(parts[:count])
            if prefix and prefix not in prefixes:
                prefixes.append(prefix)

    module_parts = module_name(root, path).split(".")[:-1]
    if module_parts:
        add_prefixes(".".join(module_parts))
    masked = strip_comments(path.read_text(encoding="utf-8"))
    for match in NAMESPACE.finditer(masked):
        add_prefixes(match.group(1))
    return prefixes


def declaration_candidates(root: Path, path: Path, name: str) -> list[str]:
    """Try enclosing namespaces before exposing a bare probe name."""
    if "." in name:
        return [name]
    return [*[
        f"{prefix}.{name}" for prefix in namespace_candidates(root, path)
    ], name]


def unknown_candidate_error(output: str, candidate: str) -> bool:
    """Return true only when Lean rejected this exact candidate as unknown."""
    markers = ("unknown constant", "unknown identifier", "unknown declaration")
    error_lines = [
        line.strip().lower()
        for line in output.splitlines()
        if "error" in line.lower()
    ]
    candidate_errors = [
        line
        for line in error_lines
        if candidate.lower() in line and any(marker in line for marker in markers)
    ]
    return bool(candidate_errors) and len(candidate_errors) == len(error_lines)


class RetryFailure(RuntimeError):
    """A namespace retry could not establish a trustworthy declaration name."""

    def __init__(
        self,
        name: str,
        path: Path,
        candidate: str,
        candidates: list[str],
        diagnostic: str,
        unresolved: bool = False,
    ) -> None:
        self.name = name
        self.path = path
        self.candidate = candidate
        self.candidates = candidates
        self.diagnostic = diagnostic
        self.unresolved = unresolved
        if unresolved:
            reason = "no namespace candidate was found"
        else:
            reason = f"candidate {candidate} failed before declaration checking"
        details = diagnostic or "(Lean returned no diagnostic output)"
        super().__init__(
            f"declaration {name} in {path}: {reason}; tried {candidates}\n{details}"
        )


def tracked_files(root: Path) -> list[Path]:
    result = subprocess.run(
        ["git", "-C", str(root), "ls-files", "ESS"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        files = [(root / value).resolve() for value in result.stdout.splitlines()]
        return sorted(path for path in files if path.suffix == ".lean" and path.is_file())
    # Without a git index (e.g. an unpacked archive), use the same scope as the
    # git branch above: the ESS library directory only. The comparator Challenge
    # and Solution cannot share one environment and are checked separately.
    return sorted(
        path.resolve()
        for path in (root / "ESS").rglob("*.lean")
        if ".lake" not in path.parts and ".git" not in path.parts
    )


def write_probe(path: Path, modules: Iterable[str], declarations: Iterable[str]) -> None:
    lines = [HEADER]
    lines.extend(f"import {module}\n" for module in modules)
    lines.extend(f"#print axioms {name}\n" for name in declarations)
    path.write_text("".join(lines), encoding="utf-8")


def run_probe(
    root: Path, modules: list[str], declarations: list[str]
) -> tuple[subprocess.CompletedProcess[str], float]:
    started = time.monotonic()
    with tempfile.TemporaryDirectory(prefix="ess-axioms-") as directory:
        probe = Path(directory) / "Axioms.lean"
        write_probe(probe, modules, declarations)
        command = [
            str(root / "scripts/lean_direct.sh"),
            str(probe),
            "-DautoImplicit=false",
            "-DwarningAsError=true",
        ]
        result = subprocess.run(command, cwd=root, text=True, capture_output=True, check=False)
    return result, time.monotonic() - started


def parse_axioms(output: str, expected: list[str]) -> tuple[dict[str, set[str]], list[str]]:
    found: dict[str, set[str]] = {}
    errors: list[str] = []
    for match in AXIOMS.finditer(output):
        if match is None:
            continue
        name = match.group("quoted") or match.group("plain")
        raw_body = match.group("body") or ""
        body = {part.strip().strip("'") for part in raw_body.split(",") if part.strip()}
        found[name] = body
    for name in expected:
        if name not in found:
            errors.append(f"missing #print axioms result for {name}")
    return found, errors


def retry_bare_declarations(
    root: Path,
    entries: list[tuple[str, Path]],
) -> tuple[list[str], list[str]]:
    """Resolve bare names through the defining module, failing closed."""
    resolved: list[str] = []
    messages: list[str] = []
    for name, path in entries:
        if "." in name:
            resolved.append(name)
            continue
        candidates = declaration_candidates(root, path, name)
        module = module_name(root, path)
        unknown_diagnostics: list[str] = []
        for candidate in candidates:
            result, _elapsed = run_probe(root, [module], [candidate])
            diagnostic = result.stdout + result.stderr
            found, _errors = parse_axioms(diagnostic, [candidate])
            if result.returncode == 0 and candidate in found:
                if candidate != name:
                    messages.append(f"check_axioms: retry resolved {name} as {candidate}")
                resolved.append(candidate)
                break
            if result.returncode != 0 and not unknown_candidate_error(diagnostic, candidate):
                raise RetryFailure(
                    name=name,
                    path=path,
                    candidate=candidate,
                    candidates=candidates,
                    diagnostic=diagnostic,
                )
            unknown_diagnostics.append(diagnostic)
        else:
            diagnostic = next((value for value in unknown_diagnostics if value), "")
            raise RetryFailure(
                name=name,
                path=path,
                candidate="none",
                candidates=candidates,
                diagnostic=diagnostic,
                unresolved=True,
            )
    return list(dict.fromkeys(resolved)), messages


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--changed",
        nargs="+",
        metavar="FILE",
        help="check only these Lean files instead of every tracked module",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()
    allowed = {"propext", "Classical.choice", "Quot.sound"}

    if args.changed:
        files = []
        for value in args.changed:
            path = (root / value).resolve() if not Path(value).is_absolute() else Path(value).resolve()
            if not path.is_file() or path.suffix != ".lean":
                print(f"check_axioms: missing Lean file {value}", file=sys.stderr)
                return 2
            files.append(path)
    else:
        files = tracked_files(root)
    files = sorted(set(files))
    if not files:
        print("check_axioms: no Lean files selected", file=sys.stderr)
        return 2

    declaration_entries: list[tuple[str, Path]] = []
    modules: list[str] = []
    for path in files:
        declaration_entries.extend((name, path) for name in public_declarations(root, path))
        modules.append(module_name(root, path))
    declarations = list(dict.fromkeys(name for name, _path in declaration_entries))
    modules = list(dict.fromkeys(modules))
    if not declarations:
        print("check_axioms: no named public declarations found", file=sys.stderr)
        return 2

    start = time.monotonic()
    result, _probe_elapsed = run_probe(root, modules, declarations)
    fallback_messages: list[str] = []
    if result.returncode != 0 and any("." not in name for name in declarations):
        try:
            declarations, fallback_messages = retry_bare_declarations(
                root, declaration_entries
            )
        except RetryFailure as failure:
            print("check_axioms: namespace retry failed", file=sys.stderr)
            print(failure, file=sys.stderr)
            return 1
        result, _probe_elapsed = run_probe(root, modules, declarations)
    elapsed = time.monotonic() - start
    output = result.stdout + result.stderr
    if result.returncode != 0:
        for message in fallback_messages:
            print(message, file=sys.stderr)
        print("check_axioms: Lean probe failed", file=sys.stderr)
        print(output, file=sys.stderr, end="" if output.endswith("\n") else "\n")
        return result.returncode
    found, parse_errors = parse_axioms(output, declarations)
    errors = list(parse_errors)
    for name, axioms in found.items():
        unexpected = axioms - allowed
        if unexpected:
            errors.append(f"{name}: unauthorized axioms {sorted(unexpected)} (full set {sorted(axioms)})")
    mode = "changed" if args.changed else "whole-tree"
    for message in fallback_messages:
        print(message)
    print(
        f"check_axioms: {mode} checked {len(files)} file(s), "
        f"{len(declarations)} declaration(s) in {elapsed:.2f}s"
    )
    if errors:
        print("check_axioms: FAIL")
        for error in errors:
            print(f"- {error}")
        return 1
    print("check_axioms: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
