-- Copyright (c) 2026 Scott Armstrong.
-- Released under Apache 2.0 license.

module

public import ESS.LPS.SmoothingFourierField
public import CKN.Leray.FourierLeray

/-!
# Ordered pressure multipliers in frequency space

The double-Riesz pressure symbol has norm at most one. A high Bessel
weight therefore absorbs every finite ordered spatial derivative of
the pressure frequency field.
-/

@[expose] public section

open CKN

open MeasureTheory FourierTransform Complex
open scoped ENNReal FourierTransform Real

set_option autoImplicit false

noncomputable section

namespace ESS

open CKN.Leray
open CKN.Foundation.Parabolic

/-- An ordered pressure Fourier field generated by a high-Bessel tensor
frequency field. -/
def lps_pressureDampedFrequency
    (n : ℕ) (α : List (Fin 3))
    (G : ComplexTensorL2) (ξ : L2Vec3) : ℂ :=
  lps_dampedFourierWordSymbol n α ξ *
    (((1 + ‖ξ‖ ^ 2) ^ (-2 : ℝ) : ℝ) : ℂ) *
      CKN.Leray.pressureApplyFormula ξ (G ξ)

/-- The ordered pressure frequency field is strongly measurable. -/
theorem lps_pressureDampedFrequency_aestronglyMeasurable
    (n : ℕ) (α : List (Fin 3)) (G : ComplexTensorL2) :
    AEStronglyMeasurable (lps_pressureDampedFrequency n α G) volume := by
  have hp : AEStronglyMeasurable
      (fun ξ : L2Vec3 => CKN.Leray.pressureApplyFormula ξ (G ξ)) volume :=
    (CKN.Leray.pressureApplyFormula_measurable.comp_aemeasurable
      (aemeasurable_id.prodMk
        (Lp.aestronglyMeasurable G).aemeasurable)).aestronglyMeasurable
  unfold lps_pressureDampedFrequency
  exact ((lps_dampedFourierWordSymbol_continuous n α).aestronglyMeasurable.mul
    CKN.Leray.regR12Weight_continuous.aestronglyMeasurable).mul hp

/-- A Bessel lift of order `2(n+2)` controls every pressure word of
length at most `2(n+1)` in frequency `L²`
(`prop:lps-smoothing`). -/
theorem lps_pressureDampedFrequency_memLp
    (n : ℕ) (α : List (Fin 3))
    (hα : α.length ≤ 2 * (n + 1)) (G : ComplexTensorL2) :
    MemLp (lps_pressureDampedFrequency n α G) 2 volume := by
  let C : ℝ := (2 * π) ^ α.length
  have hbase : MemLp (fun ξ : L2Vec3 => C * ‖(G : L2Vec3 → ComplexTensor3) ξ‖)
      2 volume := (Lp.memLp G).norm.const_mul C
  refine hbase.mono' (lps_pressureDampedFrequency_aestronglyMeasurable n α G)
    (Filter.Eventually.of_forall fun ξ => ?_)
  unfold lps_pressureDampedFrequency
  rw [norm_mul, norm_mul]
  have hb : ‖lps_dampedFourierWordSymbol n α ξ‖ *
      ‖(((1 + ‖ξ‖ ^ 2) ^ (-2 : ℝ) : ℝ) : ℂ)‖ ≤ C := by
    simpa only [norm_mul, C] using
      lps_dampedFourierWordSymbol_weighted_norm_le n α hα ξ
  have hp := CKN.Leray.pressureApplyFormula_norm_le ξ (G ξ)
  calc
    ‖lps_dampedFourierWordSymbol n α ξ‖ *
        ‖(((1 + ‖ξ‖ ^ 2) ^ (-2 : ℝ) : ℝ) : ℂ)‖ *
        ‖CKN.Leray.pressureApplyFormula ξ (G ξ)‖ ≤
      (‖lps_dampedFourierWordSymbol n α ξ‖ *
        ‖(((1 + ‖ξ‖ ^ 2) ^ (-2 : ℝ) : ℝ) : ℂ)‖) * ‖G ξ‖ := by
          exact mul_le_mul_of_nonneg_left hp (by positivity)
    _ ≤ C * ‖G ξ‖ :=
      mul_le_mul_of_nonneg_right hb (norm_nonneg _)

end ESS
